version: '3.8'
services:
  db:
    image: postgres:13.11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - pg-network

# Another services

volumes:
  db:
    driver: local

networks:
  pg-network:

